[package]
name = "guic-story"
version = "0.0.1"
description = "Native story application for GUIC."
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
gpui.workspace = true
guic = { path = "../guic", features = ["charts", "data-table", "dock", "editor", "markdown", "terminal", "tree"] }

[target.'cfg(target_os = "linux")'.dependencies]
gpui_platform = { package = "guic-gpui-platform", version = "=0.2.0", features = ["font-kit", "x11", "wayland", "runtime_shaders"] }

[target.'cfg(target_os = "macos")'.dependencies]
gpui_platform = { package = "guic-gpui-platform", version = "=0.2.0", features = ["font-kit"] }

[target.'cfg(target_os = "windows")'.dependencies]
gpui_platform = { package = "guic-gpui-platform", version = "=0.2.0" }

[lints]
workspace = true
