[package]
name = "guic-assets"
version = "0.0.1"
description = "Asset loading abstractions for GUIC."
edition.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
gpui.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
